apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-worker
  namespace: fase4
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: notifications-worker
  template:
    metadata:
      labels:
        app: notifications-worker
    spec:
      containers:
        - name: notifications-worker
          image: docker.io/adinteltidev/fase4-notifications-api:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: notifications-config
          env:
            - name: RabbitMq__Username
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: rabbitmq-user
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: rabbitmq-pass
            - name: RabbitMq__VirtualHost
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: rabbitmq-vhost
