apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
  namespace: gamestore
data:
  RabbitMq__Host: rabbitmq
  RabbitMq__Username: guest
  RabbitMq__UserCreatedQueueName: user-created-event
  QUEUE_PAYMENT_PROCESSED: payment-processed-event