apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
  namespace: fase4
data:
  RabbitMq__Host: rabbitmq
  RabbitMq__Port: "5672"
  RabbitMq__ExchangeName: fiap.events
  RabbitMq__NotificationQueueName: notification-queue
